import fs from 'fs';
import path from 'path';
import pg from 'pg';

const { Client } = pg;

interface MedicineSeed {
  brand_name: string;
  generic_name: string;
  dosage_form: string;
  strength: string;
  price: number;
  currency: string;
  package_info: string;
  therapeutic_class: string;
  indications: string;
  dosage_and_administration: string;
  side_effects: string;
  precautions: string;
  producer_name: string;
  producer_country: string;
  producer_website?: string;
}

// ----------------------------------------------------------------------
// Master Medicines Catalog (Bangladesh Pharmaceuticals Top Priority + Global)
// ----------------------------------------------------------------------
const MEDICINES_DATASET: MedicineSeed[] = [
  // ====================================================================
  // 1. ANALGESICS, ANTIPYRETICS & NSAIDs
  // ====================================================================
  // Paracetamol
  {
    brand_name: "Ace",
    generic_name: "Paracetamol",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 1.20,
    currency: "BDT",
    package_info: "10 x 50 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Fever, headache, toothache, body ache, dysmenorrhea, backache and flu-like symptoms.",
    dosage_and_administration: "Adults: 1-2 tablets (500-1000 mg) every 4-6 hours as needed. Maximum 4000 mg daily.",
    side_effects: "Very rare in therapeutic doses. Rarely allergic skin rashes. High overdose may cause hepatic failure.",
    precautions: "Caution in chronic alcoholics and patients with impaired hepatic or renal function.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Ace Plus",
    generic_name: "Paracetamol + Caffeine",
    dosage_form: "Tablet",
    strength: "500 mg + 65 mg",
    price: 2.50,
    currency: "BDT",
    package_info: "10 x 20 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Fast relief from migraine, severe headache, tension headache, toothache, and menstrual cramps.",
    dosage_and_administration: "Adults & children over 12: 1-2 tablets every 4-6 hours as needed. Maximum 8 tablets in 24 hours.",
    side_effects: "Mild palpitations, restlessness, insomnia due to caffeine. Rare allergic dermatitis.",
    precautions: "Limit intake of caffeine-rich drinks like coffee, energy drinks, and strong tea while taking this medication.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Ace Power",
    generic_name: "Paracetamol (Extended Release)",
    dosage_form: "Tablet",
    strength: "665 mg",
    price: 2.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Continuous 8-hour relief from chronic muscular pain, osteoarthritis, back pain, and joint stiffness.",
    dosage_and_administration: "Adults: 2 tablets swallowed whole every 8 hours. Do not chew or crush.",
    side_effects: "Mild stomach discomfort, rarely skin hypersensitivity.",
    precautions: "Do not chew, break, or crush sustained-release tablets.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Ace Syrup",
    generic_name: "Paracetamol",
    dosage_form: "Syrup",
    strength: "120 mg/5 ml",
    price: 35.00,
    currency: "BDT",
    package_info: "60 ml bottle",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Pediatric fever, post-immunization pyrexia, teething pain, and mild aches in infants and children.",
    dosage_and_administration: "Children 3 months - 1 year: 2.5-5 ml; 1-5 years: 5-10 ml; 6-12 years: 10-20 ml every 4-6 hours.",
    side_effects: "Generally very well tolerated in children.",
    precautions: "Use calibrated measuring cup. Do not exceed 4 doses in 24 hours.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Napa",
    generic_name: "Paracetamol",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 1.20,
    currency: "BDT",
    package_info: "10 x 50 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Primary analgesic for pain, headache, dental discomfort, post-operative ache, and acute fever.",
    dosage_and_administration: "Adults: 1-2 tablets every 4-6 hours as necessary. Maximum 4g daily.",
    side_effects: "Well tolerated. Rare cutaneous allergic reactions.",
    precautions: "Avoid taking multiple concurrent medications containing acetaminophen or paracetamol.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Napa Extra",
    generic_name: "Paracetamol + Caffeine",
    dosage_form: "Tablet",
    strength: "500 mg + 65 mg",
    price: 2.50,
    currency: "BDT",
    package_info: "10 x 20 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Acute migraine attacks, throbbing headache, muscular soreness, and flu-associated aches.",
    dosage_and_administration: "Adults: 1-2 tablets every 4-6 hours. Maximum 8 tablets per day.",
    side_effects: "Restlessness, mild tachycardia from caffeine.",
    precautions: "Avoid bedtime administration if sensitive to caffeine-induced insomnia.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Napa Extend",
    generic_name: "Paracetamol (Extended Release)",
    dosage_form: "Tablet",
    strength: "665 mg",
    price: 2.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Sustained joint and spinal pain alleviation for osteoarthritis and degenerative disorders.",
    dosage_and_administration: "Adults: 2 tablets every 8 hours with full glass of water.",
    side_effects: "Mild GI irritation, rarely pruritus.",
    precautions: "Swallow tablets whole without chewing or halving.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Napa Rapid",
    generic_name: "Paracetamol (Actizorb)",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 1.50,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Ultra-fast disintegration technology for rapid absorption within 10 minutes.",
    dosage_and_administration: "1-2 tablets every 4-6 hours with water.",
    side_effects: "Minimal side effects at recommended dosages.",
    precautions: "Do not exceed maximum daily dosage.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Fast",
    generic_name: "Paracetamol",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 1.20,
    currency: "BDT",
    package_info: "10 x 50 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Relief of fever, common cold aches, tooth extraction pain, and muscle soreness.",
    dosage_and_administration: "Adults: 1-2 tablets every 4-6 hours. Max 8 tablets daily.",
    side_effects: "Infrequent allergic rash.",
    precautions: "Consult physician if fever persists over 3 consecutive days.",
    producer_name: "The Acme Laboratories Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.acmeglobal.com"
  },
  {
    brand_name: "Fast XR",
    generic_name: "Paracetamol (Extended Release)",
    dosage_form: "Tablet",
    strength: "665 mg",
    price: 2.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Prolonged pain control in chronic musculoskeletal conditions.",
    dosage_and_administration: "Adults: 2 tablets every 8 hours.",
    side_effects: "Rare cutaneous reactions.",
    precautions: "Do not crush or crush before ingestion.",
    producer_name: "The Acme Laboratories Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.acmeglobal.com"
  },
  {
    brand_name: "Reset",
    generic_name: "Paracetamol",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 1.20,
    currency: "BDT",
    package_info: "10 x 50 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Rapid pain reduction and antipyretic control.",
    dosage_and_administration: "Adults: 500-1000 mg every 4-6 hours as needed.",
    side_effects: "Very safe. Rarely nausea.",
    precautions: "Patients with G6PD deficiency should use caution.",
    producer_name: "Incepta Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.inceptapharma.com"
  },
  {
    brand_name: "Panadol",
    generic_name: "Paracetamol",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 3.50,
    currency: "GBP",
    package_info: "2 x 12 tablets",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Global OTC brand for treatment of fever, tension headache, and period pain.",
    dosage_and_administration: "Adults: 1-2 tablets every 4 to 6 hours.",
    side_effects: "Rare skin rash, neutropenia.",
    precautions: "Do not use with other paracetamol products.",
    producer_name: "GlaxoSmithKline (GSK)",
    producer_country: "United Kingdom",
    producer_website: "https://www.gsk.com"
  },
  {
    brand_name: "Tylenol",
    generic_name: "Paracetamol",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 7.99,
    currency: "USD",
    package_info: "100 caplets bottle",
    therapeutic_class: "Analgesics & Antipyretics",
    indications: "Pain reliever and fever reducer for minor aches, arthritis, and colds.",
    dosage_and_administration: "Adults: 2 caplets every 6 hours while symptoms last.",
    side_effects: "Severe liver damage may occur if excessive dose is ingested.",
    precautions: "FDA warning against combining with 3 or more alcoholic drinks daily.",
    producer_name: "Johnson & Johnson",
    producer_country: "United States",
    producer_website: "https://www.jnj.com"
  },

  // Ibuprofen & NSAIDs
  {
    brand_name: "Flamgo",
    generic_name: "Ibuprofen",
    dosage_form: "Tablet",
    strength: "400 mg",
    price: 2.20,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Rheumatoid arthritis, osteoarthritis, acute gout, dental pain, and soft-tissue injuries.",
    dosage_and_administration: "Adults: 400-800 mg 3-4 times daily after meals. Maximum 2400 mg daily.",
    side_effects: "Epigastric distress, heartburn, nausea, gastric ulceration with long-term use.",
    precautions: "Contraindicated in active peptic ulcer disease and severe heart failure. Take with food.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Profen",
    generic_name: "Ibuprofen",
    dosage_form: "Tablet",
    strength: "400 mg",
    price: 2.20,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Musculoskeletal inflammation, dental extraction pain, dysmenorrhea, and inflammatory swelling.",
    dosage_and_administration: "Adults: 1 tablet 3 times daily after food.",
    side_effects: "Dyspepsia, dizziness, fluid retention.",
    precautions: "Monitor blood pressure in hypertensive patients on long-term therapy.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Advil",
    generic_name: "Ibuprofen",
    dosage_form: "Tablet",
    strength: "200 mg",
    price: 9.50,
    currency: "USD",
    package_info: "50 coated tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Fast liquid-filled relief for back pain, muscle inflammation, and headache.",
    dosage_and_administration: "Adults: 1-2 tablets every 4 to 6 hours as needed.",
    side_effects: "Stomach upset, risk of gastrointestinal bleeding.",
    precautions: "Avoid use during third trimester of pregnancy.",
    producer_name: "Pfizer Inc.",
    producer_country: "United States",
    producer_website: "https://www.pfizer.com"
  },
  {
    brand_name: "Brufen",
    generic_name: "Ibuprofen",
    dosage_form: "Tablet",
    strength: "400 mg",
    price: 4.80,
    currency: "EUR",
    package_info: "30 film-coated tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Original global ibuprofen formulation for inflammatory rheumatological conditions.",
    dosage_and_administration: "Adults: 400 mg 3 times daily after food.",
    side_effects: "Gastrointestinal ulceration, tinnitus, hypertension.",
    precautions: "Use lowest effective dose for shortest necessary duration.",
    producer_name: "Abbott Laboratories",
    producer_country: "United States",
    producer_website: "https://www.abbott.com"
  },

  // Naproxen
  {
    brand_name: "Napryn",
    generic_name: "Naproxen Sodium",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 7.00,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Acute gouty arthritis, ankylosing spondylitis, bursitis, tendinitis, and severe menstrual pain.",
    dosage_and_administration: "Initial 500-750 mg followed by 250-500 mg every 12 hours after meals.",
    side_effects: "Gastric upset, peptic ulcers, headache, drowsiness.",
    precautions: "Co-prescribe with a PPI (e.g., Esomeprazole) in patients with GI risk factors.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Xenapro",
    generic_name: "Naproxen Sodium",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 7.00,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Post-traumatic swelling, joint inflammation, and chronic arthritic discomfort.",
    dosage_and_administration: "500 mg twice daily with food.",
    side_effects: "Heartburn, fluid retention, nausea.",
    precautions: "Contraindicated in patients with active gastrointestinal bleeding.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Aleve",
    generic_name: "Naproxen Sodium",
    dosage_form: "Tablet",
    strength: "220 mg",
    price: 8.50,
    currency: "USD",
    package_info: "100 caplets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "12-hour pain relief from minor arthritis pain, headache, and fever.",
    dosage_and_administration: "1 caplet every 8 to 12 hours with full glass of water.",
    side_effects: "GI bleeding risks, edema, dizziness.",
    precautions: "Do not exceed 2 caplets in any 8-to-12 hour period.",
    producer_name: "Bayer AG",
    producer_country: "Germany",
    producer_website: "https://www.bayer.com"
  },

  // Aceclofenac & Ketorolac
  {
    brand_name: "Flexi",
    generic_name: "Aceclofenac",
    dosage_form: "Tablet",
    strength: "100 mg",
    price: 5.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Superior GI-tolerated NSAID for osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis.",
    dosage_and_administration: "Adults: 100 mg twice daily (one in morning and one in evening) after meals.",
    side_effects: "Abdominal discomfort, dizziness, elevated liver enzymes in rare cases.",
    precautions: "Avoid in severe heart failure, ischemic heart disease, and peripheral arterial disease.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Mervan",
    generic_name: "Aceclofenac",
    dosage_form: "Tablet",
    strength: "100 mg",
    price: 5.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Painful inflammatory conditions of joints, back, and dental extraction sites.",
    dosage_and_administration: "100 mg twice daily with water.",
    side_effects: "Mild dyspepsia, flatulence.",
    precautions: "Monitor renal function in elderly patients.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Rolac",
    generic_name: "Ketorolac Tromethamine",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 12.00,
    currency: "BDT",
    package_info: "2 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Short-term management of moderate to severe acute post-operative, orthopedic, and dental pain.",
    dosage_and_administration: "10 mg every 4-6 hours as needed. Maximum 40 mg daily. Duration must NOT exceed 5 days.",
    side_effects: "Severe peptic ulcer risk if used beyond 5 days, gastrointestinal perforation, renal toxicity.",
    precautions: "STRICT LIMIT: Maximum 5 days use. Contraindicated in peptic ulcer history or renal failure.",
    producer_name: "Incepta Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.inceptapharma.com"
  },
  {
    brand_name: "Torax",
    generic_name: "Ketorolac Tromethamine",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 12.00,
    currency: "BDT",
    package_info: "2 x 10 tablets",
    therapeutic_class: "Non-Steroidal Anti-Inflammatory Drug (NSAID)",
    indications: "Acute traumatic pain and intense surgical convalescent analgesia.",
    dosage_and_administration: "10 mg every 6 hours. Do not exceed 5 days duration.",
    side_effects: "Gastric hemorrhage, acute kidney injury in dehydrated patients.",
    precautions: "Ensure adequate patient hydration. Never use for chronic long-term conditions.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },

  // Aspirin / Ecosprin
  {
    brand_name: "Ecosprin",
    generic_name: "Aspirin (Low Dose)",
    dosage_form: "Tablet",
    strength: "75 mg",
    price: 0.80,
    currency: "BDT",
    package_info: "10 x 30 enteric-coated tablets",
    therapeutic_class: "Antiplatelet & Cardiovascular Agent",
    indications: "Secondary prevention of myocardial infarction, ischemic stroke, and transient ischemic attacks (TIA).",
    dosage_and_administration: "1 tablet (75 mg) once daily swallowed whole with a glass of water after food.",
    side_effects: "Gastric irritation, microbleeding, prolonged bleeding time.",
    precautions: "Contraindicated in children under 16 due to Reye's syndrome risk. Caution with other blood thinners.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Aspirin Protect",
    generic_name: "Aspirin (Low Dose)",
    dosage_form: "Tablet",
    strength: "100 mg",
    price: 3.20,
    currency: "EUR",
    package_info: "28 enteric-coated tablets",
    therapeutic_class: "Antiplatelet & Cardiovascular Agent",
    indications: "Prophylaxis of thromboembolism and coronary arterial thrombosis.",
    dosage_and_administration: "1 tablet daily after food.",
    side_effects: "Gastrointestinal discomfort, occult blood loss.",
    precautions: "Do not stop abruptly without cardiologist recommendation.",
    producer_name: "Bayer AG",
    producer_country: "Germany",
    producer_website: "https://www.bayer.com"
  },

  // ====================================================================
  // 2. GASTROINTESTINAL, ACID PEPTIC & ANTI-ULCERANTS
  // ====================================================================
  // Omeprazole
  {
    brand_name: "Seclo",
    generic_name: "Omeprazole",
    dosage_form: "Capsule",
    strength: "20 mg",
    price: 5.00,
    currency: "BDT",
    package_info: "10 x 10 capsules",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Gastroesophageal reflux disease (GERD), duodenal ulcer, gastric ulcer, and H. pylori eradication.",
    dosage_and_administration: "Adults: 20 mg once daily before breakfast for 4-8 weeks. Severe reflux: 40 mg daily.",
    side_effects: "Headache, diarrhea, constipation, abdominal pain, flatulence. Long-term use may lower B12 and magnesium.",
    precautions: "Take on empty stomach 30-60 minutes before first meal for optimal acid suppression.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Losectil",
    generic_name: "Omeprazole",
    dosage_form: "Capsule",
    strength: "20 mg",
    price: 5.00,
    currency: "BDT",
    package_info: "10 x 10 capsules",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Acid hypersecretion, peptic ulcers, heartburn, and prevention of NSAID-induced ulcers.",
    dosage_and_administration: "20 mg once daily 30 minutes before meal.",
    side_effects: "Mild abdominal cramping, nausea.",
    precautions: "Long term PPI therapy (>1 year) may increase fracture risk in osteoporosis.",
    producer_name: "Incepta Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.inceptapharma.com"
  },
  {
    brand_name: "Proceptin",
    generic_name: "Omeprazole",
    dosage_form: "Capsule",
    strength: "20 mg",
    price: 5.00,
    currency: "BDT",
    package_info: "10 x 10 capsules",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Erosive esophagitis and maintenance of acid reduction.",
    dosage_and_administration: "20 mg once daily in morning.",
    side_effects: "Headache, rare rash.",
    precautions: "Swallow whole with water; do not open or crush micro-pellets.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Prilosec",
    generic_name: "Omeprazole",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 18.50,
    currency: "USD",
    package_info: "42 delayed-release tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Frequent heartburn occurring 2 or more days a week.",
    dosage_and_administration: "1 tablet once daily before morning meal for a 14-day course.",
    side_effects: "Headache, dry mouth, hypomagnesemia on prolonged usage.",
    precautions: "Do not repeat 14-day OTC course more often than every 4 months unless directed by doctor.",
    producer_name: "AstraZeneca",
    producer_country: "United Kingdom",
    producer_website: "https://www.astrazeneca.com"
  },

  // Esomeprazole
  {
    brand_name: "Maxpro",
    generic_name: "Esomeprazole Magnesium",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 7.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Erosive esophagitis, Zollinger-Ellison syndrome, GERD relief, and triple therapy for H. pylori.",
    dosage_and_administration: "Adults: 20-40 mg once daily 30-60 minutes before breakfast for 4-8 weeks.",
    side_effects: "Headache, nausea, abdominal pain, diarrhea. Long term: Clostridium difficile risk.",
    precautions: "May interact with clopidogrel by reducing its antiplatelet efficacy.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Maxpro 40",
    generic_name: "Esomeprazole Magnesium",
    dosage_form: "Tablet",
    strength: "40 mg",
    price: 10.00,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Severe erosive reflux esophagitis, active duodenal ulcers, and Zollinger-Ellison syndrome.",
    dosage_and_administration: "40 mg once daily for 4-8 weeks before meal.",
    side_effects: "Headache, flatulence, dry mouth.",
    precautions: "Monitor bone mineral density with multi-year high dose usage.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Nexum",
    generic_name: "Esomeprazole Magnesium",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 7.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Potent S-isomer acid pump inhibition for chronic reflux and nocturnal acid breakthrough.",
    dosage_and_administration: "20 mg once daily before meals.",
    side_effects: "Mild dizziness, loose stools.",
    precautions: "Take before breakfast with water.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Sergel",
    generic_name: "Esomeprazole Magnesium",
    dosage_form: "Capsule",
    strength: "20 mg",
    price: 7.00,
    currency: "BDT",
    package_info: "10 x 10 capsules",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Acid reflux disease, heartburn, and NSAID-related stomach ulcer prevention.",
    dosage_and_administration: "20 mg once daily 30 minutes before meal.",
    side_effects: "Nausea, headache, mild abdominal ache.",
    precautions: "Do not chew pellets inside capsules.",
    producer_name: "Healthcare Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.hplbd.com"
  },
  {
    brand_name: "Nexium",
    generic_name: "Esomeprazole Magnesium",
    dosage_form: "Tablet",
    strength: "40 mg",
    price: 24.00,
    currency: "GBP",
    package_info: "28 gastro-resistant tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "The original reference esomeprazole brand for erosive reflux and ulcer healing.",
    dosage_and_administration: "40 mg once daily for 4 weeks.",
    side_effects: "Headache, GI disturbance, peripheral edema.",
    precautions: "Prescription required; check for drug-drug interactions with ketoconazole and diazepam.",
    producer_name: "AstraZeneca",
    producer_country: "United Kingdom",
    producer_website: "https://www.astrazeneca.com"
  },

  // Pantoprazole
  {
    brand_name: "Pantobex",
    generic_name: "Pantoprazole Sodium",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 6.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Gastric ulcer, duodenal ulcer, reflux esophagitis. Minimal CYP2C19 drug interactions.",
    dosage_and_administration: "Adults: 20-40 mg once daily before morning meal.",
    side_effects: "Headache, diarrhea, dry mouth, arthralgia.",
    precautions: "Preferred PPI in cardiac patients receiving Clopidogrel due to lowest CYP2C19 competition.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Trupan",
    generic_name: "Pantoprazole Sodium",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 6.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Acid reflux disease, gastritis, and hypersecretory digestive conditions.",
    dosage_and_administration: "20-40 mg once daily in morning.",
    side_effects: "Well tolerated. Rare rash.",
    precautions: "Swallow whole. Do not chew.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Protonix",
    generic_name: "Pantoprazole Sodium",
    dosage_form: "Tablet",
    strength: "40 mg",
    price: 16.50,
    currency: "USD",
    package_info: "30 delayed-release tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Treatment of erosive esophagitis associated with GERD.",
    dosage_and_administration: "40 mg once daily for up to 8 weeks.",
    side_effects: "Headache, diarrhea, flatulence.",
    precautions: "Monitor serum magnesium levels with prolonged treatment.",
    producer_name: "Pfizer Inc.",
    producer_country: "United States",
    producer_website: "https://www.pfizer.com"
  },
  {
    brand_name: "Pantocid",
    generic_name: "Pantoprazole Sodium",
    dosage_form: "Tablet",
    strength: "40 mg",
    price: 15.00,
    currency: "INR",
    package_info: "1 x 15 tablets",
    therapeutic_class: "Proton Pump Inhibitor (PPI)",
    indications: "Gastrointestinal acid reduction, peptic ulcers, and reflux management.",
    dosage_and_administration: "1 tablet once daily before meal.",
    side_effects: "Dizziness, diarrhea, nausea.",
    precautions: "Take before food.",
    producer_name: "Sun Pharmaceutical Industries",
    producer_country: "India",
    producer_website: "https://www.sunpharma.com"
  },

  // Motility & Antiemetic: Domperidone & Ondansetron
  {
    brand_name: "Motigut",
    generic_name: "Domperidone",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 3.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Prokinetic & Antiemetic",
    indications: "Delayed gastric emptying, bloating, nausea, vomiting, feeling of early fullness and upper abdominal discomfort.",
    dosage_and_administration: "Adults: 10 mg 3 times daily, 15-30 minutes before meals. Maximum 30 mg daily.",
    side_effects: "Dry mouth, rarely galactorrhea or gynecomastia. Risk of QT prolongation at high doses.",
    precautions: "Contraindicated in cardiac disease, prolonged QT interval, and GI hemorrhage.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Omidon",
    generic_name: "Domperidone",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 3.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Prokinetic & Antiemetic",
    indications: "Nausea, vomiting, dyspeptic symptom complex associated with delayed stomach clearance.",
    dosage_and_administration: "10 mg 3 times daily before meals.",
    side_effects: "Headache, transient abdominal cramps.",
    precautions: "Use lowest effective dose for shortest duration.",
    producer_name: "Incepta Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.inceptapharma.com"
  },
  {
    brand_name: "Emistat",
    generic_name: "Ondansetron",
    dosage_form: "Tablet",
    strength: "8 mg",
    price: 10.00,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Antiemetic (5-HT3 Antagonist)",
    indications: "Prevention of nausea and vomiting associated with chemotherapy, radiation therapy, and post-operative surgery.",
    dosage_and_administration: "Adults: 8 mg 1-2 hours before therapy, then 8 mg every 12 hours for up to 5 days.",
    side_effects: "Constipation, headache, sensation of warmth or flushing.",
    precautions: "Monitor ECG in patients with congenital long QT syndrome or hypokalemia.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Zofran",
    generic_name: "Ondansetron",
    dosage_form: "Tablet",
    strength: "8 mg",
    price: 21.00,
    currency: "EUR",
    package_info: "10 orally disintegrating tablets",
    therapeutic_class: "Antiemetic (5-HT3 Antagonist)",
    indications: "Original reference anti-nausea therapy for cytotoxic chemotherapy and surgery.",
    dosage_and_administration: "8 mg twice daily.",
    side_effects: "Constipation, headache, transient hypotension.",
    precautions: "Avoid concomitant use with apomorphine.",
    producer_name: "Novartis",
    producer_country: "Switzerland",
    producer_website: "https://www.novartis.com"
  },

  // ====================================================================
  // 3. CARDIOVASCULAR & ANTIHYPERTENSIVES
  // ====================================================================
  // Amlodipine
  {
    brand_name: "Camlosan",
    generic_name: "Amlodipine Besylate",
    dosage_form: "Tablet",
    strength: "5 mg",
    price: 4.50,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Calcium Channel Blocker (Dihydropyridine)",
    indications: "Essential hypertension, chronic stable angina, and vasospastic (Prinzmetal's) angina.",
    dosage_and_administration: "Initial: 5 mg once daily. May increase to maximum 10 mg once daily according to patient response.",
    side_effects: "Peripheral edema (ankle swelling), flushing, dizziness, fatigue, palpitations.",
    precautions: "Monitor for peripheral edema. Caution in severe hepatic impairment and aortic stenosis.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Amlocard",
    generic_name: "Amlodipine Besylate",
    dosage_form: "Tablet",
    strength: "5 mg",
    price: 4.50,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Calcium Channel Blocker (Dihydropyridine)",
    indications: "Blood pressure control and reduction of angina frequency.",
    dosage_and_administration: "5 mg once daily.",
    side_effects: "Ankle edema, headache, flushing.",
    precautions: "Do not discontinue abruptly without medical advice.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Norvasc",
    generic_name: "Amlodipine Besylate",
    dosage_form: "Tablet",
    strength: "5 mg",
    price: 15.00,
    currency: "USD",
    package_info: "30 tablets bottle",
    therapeutic_class: "Calcium Channel Blocker (Dihydropyridine)",
    indications: "Global reference amlodipine for 24-hour blood pressure reduction.",
    dosage_and_administration: "5-10 mg once daily.",
    side_effects: "Dose-dependent pedal edema, somnolence.",
    precautions: "Dose titration should occur every 7-14 days.",
    producer_name: "Pfizer Inc.",
    producer_country: "United States",
    producer_website: "https://www.pfizer.com"
  },

  // Losartan Potassium
  {
    brand_name: "Angilock",
    generic_name: "Losartan Potassium",
    dosage_form: "Tablet",
    strength: "50 mg",
    price: 7.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Angiotensin II Receptor Blocker (ARB)",
    indications: "Hypertension, diabetic nephropathy in type 2 diabetes with proteinuria, and stroke risk reduction.",
    dosage_and_administration: "Adults: Usually 50 mg once daily. May increase to 100 mg once daily if needed.",
    side_effects: "Dizziness, hyperkalemia, hypotension, nasal congestion.",
    precautions: "STRICTLY CONTRAINDICATED in pregnancy (causes fetal toxicity/death). Monitor serum potassium.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Osartil",
    generic_name: "Losartan Potassium",
    dosage_form: "Tablet",
    strength: "50 mg",
    price: 7.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Angiotensin II Receptor Blocker (ARB)",
    indications: "Blood pressure regulation and renal preservation in hypertensive diabetics.",
    dosage_and_administration: "50 mg once daily.",
    side_effects: "Hypotension on first dose, lightheadedness.",
    precautions: "Do not take during pregnancy. Avoid potassium supplements unless instructed.",
    producer_name: "Incepta Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.inceptapharma.com"
  },
  {
    brand_name: "Cozaar",
    generic_name: "Losartan Potassium",
    dosage_form: "Tablet",
    strength: "50 mg",
    price: 22.00,
    currency: "USD",
    package_info: "30 tablets",
    therapeutic_class: "Angiotensin II Receptor Blocker (ARB)",
    indications: "Reference ARB for hypertension and protection of kidney function.",
    dosage_and_administration: "50 mg once daily.",
    side_effects: "Fatigue, hyperkalemia.",
    precautions: "Boxed warning: Discontinue immediately if pregnancy detected.",
    producer_name: "Merck & Co. (MSD)",
    producer_country: "United States",
    producer_website: "https://www.merck.com"
  },

  // Bisoprolol
  {
    brand_name: "Bisotop",
    generic_name: "Bisoprolol Fumarate",
    dosage_form: "Tablet",
    strength: "2.5 mg",
    price: 5.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Beta-1 Selective Adrenoceptor Blocker",
    indications: "Hypertension, chronic stable angina, and adjunct treatment of stable chronic heart failure with reduced ejection fraction.",
    dosage_and_administration: "Hypertension/Angina: 5-10 mg once daily. Heart failure: start low at 1.25 mg daily and titrate carefully.",
    side_effects: "Bradycardia (slow heart rate), cold extremities, fatigue, dizziness, hypotension.",
    precautions: "Do not discontinue abruptly (risk of rebound tachycardia and MI). Caution in asthma or COPD.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Cardicor",
    generic_name: "Bisoprolol Fumarate",
    dosage_form: "Tablet",
    strength: "2.5 mg",
    price: 5.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Beta-1 Selective Adrenoceptor Blocker",
    indications: "Heart rate regulation in cardiac insufficiency and arterial hypertension.",
    dosage_and_administration: "2.5-5 mg once daily in the morning.",
    side_effects: "Fatigue, low pulse, cold feet.",
    precautions: "Check resting heart rate before administration.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Concor",
    generic_name: "Bisoprolol Fumarate",
    dosage_form: "Tablet",
    strength: "5 mg",
    price: 12.50,
    currency: "EUR",
    package_info: "30 film-coated tablets",
    therapeutic_class: "Beta-1 Selective Adrenoceptor Blocker",
    indications: "Original European reference bisoprolol for cardioselective beta blockade.",
    dosage_and_administration: "5 mg once daily in morning.",
    side_effects: "Bradycardia, sleep disturbance, asthenia.",
    precautions: "Gradual step-wise dose reduction over 2 weeks when stopping.",
    producer_name: "Novartis",
    producer_country: "Switzerland",
    producer_website: "https://www.novartis.com"
  },

  // Atorvastatin & Rosuvastatin (Lipid-Lowering)
  {
    brand_name: "Anzitor",
    generic_name: "Atorvastatin Calcium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 10.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "HMG-CoA Reductase Inhibitor (Statin)",
    indications: "Primary hypercholesterolemia, mixed dyslipidemia, and prevention of cardiovascular events in coronary heart disease.",
    dosage_and_administration: "Initial: 10-20 mg once daily at bedtime. May be increased up to 80 mg daily depending on target LDL.",
    side_effects: "Myalgia (muscle ache), elevated transaminases, nasopharyngitis, arthralgia. Rare rhabdomyolysis.",
    precautions: "Report unexplained muscle tenderness or weakness immediately. Contraindicated in active liver disease and pregnancy.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Atova",
    generic_name: "Atorvastatin Calcium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 10.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "HMG-CoA Reductase Inhibitor (Statin)",
    indications: "Lowering elevated total cholesterol, LDL-C, triglycerides, and increasing HDL-C.",
    dosage_and_administration: "10-20 mg once daily at night.",
    side_effects: "Muscle soreness, constipation, mild headache.",
    precautions: "Perform baseline liver function tests before starting therapy.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Lipitor",
    generic_name: "Atorvastatin Calcium",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 25.00,
    currency: "USD",
    package_info: "30 tablets bottle",
    therapeutic_class: "HMG-CoA Reductase Inhibitor (Statin)",
    indications: "World-renowned statin for atherosclerotic cardiovascular risk reduction.",
    dosage_and_administration: "20 mg once daily at bedtime.",
    side_effects: "Myopathy, elevated blood glucose.",
    precautions: "Contraindicated in pregnant or nursing women.",
    producer_name: "Pfizer Inc.",
    producer_country: "United States",
    producer_website: "https://www.pfizer.com"
  },
  {
    brand_name: "Rostar",
    generic_name: "Rosuvastatin Calcium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 15.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "HMG-CoA Reductase Inhibitor (Statin)",
    indications: "High-intensity statin for severe hypercholesterolemia and slow progression of atherosclerosis.",
    dosage_and_administration: "Adults: 5-10 mg once daily any time of day with or without food. Maximum 20-40 mg daily.",
    side_effects: "Myalgia, headache, nausea, proteinuria.",
    precautions: "Start at 5 mg in Asian patients due to higher plasma exposure levels.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Crestor",
    generic_name: "Rosuvastatin Calcium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 28.00,
    currency: "GBP",
    package_info: "28 film-coated tablets",
    therapeutic_class: "HMG-CoA Reductase Inhibitor (Statin)",
    indications: "Original reference rosuvastatin for intensive LDL reduction.",
    dosage_and_administration: "10 mg once daily.",
    side_effects: "Muscle pain, weakness, abdominal pain.",
    precautions: "Monitor creatine kinase in patients presenting with myalgias.",
    producer_name: "AstraZeneca",
    producer_country: "United Kingdom",
    producer_website: "https://www.astrazeneca.com"
  },

  // Clopidogrel (Antiplatelet)
  {
    brand_name: "Anclog",
    generic_name: "Clopidogrel Bisulfate",
    dosage_form: "Tablet",
    strength: "75 mg",
    price: 12.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Antiplatelet Agent (P2Y12 Inhibitor)",
    indications: "Prevention of atherothrombotic events in patients with recent myocardial infarction, stroke, or peripheral artery disease.",
    dosage_and_administration: "75 mg once daily with or without food. In acute coronary syndrome: 300 mg loading dose, then 75 mg daily.",
    side_effects: "Bleeding (bruising, hematoma, epistaxis), gastrointestinal hemorrhage, purpura.",
    precautions: "Discontinue 5-7 days before elective major surgery to avoid excessive surgical bleeding.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Plavix",
    generic_name: "Clopidogrel Bisulfate",
    dosage_form: "Tablet",
    strength: "75 mg",
    price: 26.00,
    currency: "EUR",
    package_info: "28 film-coated tablets",
    therapeutic_class: "Antiplatelet Agent (P2Y12 Inhibitor)",
    indications: "Original reference P2Y12 inhibitor for stent thrombosis prevention and acute coronary syndromes.",
    dosage_and_administration: "75 mg once daily with food.",
    side_effects: "Hemorrhage, thrombotic thrombocytopenic purpura (rare).",
    precautions: "Avoid concurrent use with strong CYP2C19 inhibitors like omeprazole.",
    producer_name: "Sanofi",
    producer_country: "France",
    producer_website: "https://www.sanofi.com"
  },

  // ====================================================================
  // 4. DIABETES & METABOLIC DISORDERS
  // ====================================================================
  // Metformin
  {
    brand_name: "Comet",
    generic_name: "Metformin Hydrochloride",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 4.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Antidiabetic (Biguanide)",
    indications: "First-line oral treatment for type 2 diabetes mellitus, particularly in overweight and obese patients.",
    dosage_and_administration: "Initial: 500 mg 1-2 times daily with or after meals. Maximum 2550 mg daily in divided doses.",
    side_effects: "Gastrointestinal disturbances (diarrhea, nausea, metallic taste, bloating). Very rare lactic acidosis.",
    precautions: "Take WITH or AFTER meals to minimize GI side effects. Contraindicated in severe renal impairment (eGFR < 30).",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Comet XR",
    generic_name: "Metformin Hydrochloride (Extended Release)",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 5.50,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Antidiabetic (Biguanide)",
    indications: "Extended-release formulation for superior gastrointestinal tolerability in type 2 diabetes.",
    dosage_and_administration: "500-1000 mg once daily with evening meal.",
    side_effects: "Greatly reduced GI complaints compared to immediate-release metformin.",
    precautions: "Swallow whole with dinner; do not crush or break.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Dianorm",
    generic_name: "Metformin Hydrochloride",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 4.00,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Antidiabetic (Biguanide)",
    indications: "Glycemic control and insulin sensitivity improvement.",
    dosage_and_administration: "500 mg twice daily with food.",
    side_effects: "Flatulence, loose stools, nausea.",
    precautions: "Temporarily withhold prior to iodinated radiocontrast imaging procedures.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Glucophage",
    generic_name: "Metformin Hydrochloride",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 8.50,
    currency: "EUR",
    package_info: "50 film-coated tablets",
    therapeutic_class: "Antidiabetic (Biguanide)",
    indications: "Original reference metformin formulation for type 2 diabetes management.",
    dosage_and_administration: "500-850 mg 2-3 times daily during or after meals.",
    side_effects: "Gastrointestinal intolerance, vitamin B12 malabsorption with long-term therapy.",
    precautions: "Boxed warning for lactic acidosis risk in renal failure or severe dehydration.",
    producer_name: "Merck & Co. (MSD)",
    producer_country: "United States",
    producer_website: "https://www.merck.com"
  },

  // Sitagliptin & Linagliptin (DPP-4 Inhibitors)
  {
    brand_name: "Sitaglip",
    generic_name: "Sitagliptin Phosphate",
    dosage_form: "Tablet",
    strength: "50 mg",
    price: 15.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Dipeptidyl Peptidase-4 (DPP-4) Inhibitor",
    indications: "Monotherapy or in combination with metformin/sulfonylureas for glycemic control without causing hypoglycemia.",
    dosage_and_administration: "100 mg once daily with or without food. Reduce dose to 50 mg or 25 mg in renal insufficiency.",
    side_effects: "Upper respiratory tract infection, nasopharyngitis, headache. Rare pancreatitis.",
    precautions: "Discontinue immediately if severe, persistent abdominal pain radiating to the back occurs (pancreatitis).",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Januvia",
    generic_name: "Sitagliptin Phosphate",
    dosage_form: "Tablet",
    strength: "100 mg",
    price: 45.00,
    currency: "USD",
    package_info: "30 tablets bottle",
    therapeutic_class: "Dipeptidyl Peptidase-4 (DPP-4) Inhibitor",
    indications: "Gold standard reference DPP-4 inhibitor for type 2 diabetes mellitus.",
    dosage_and_administration: "100 mg once daily.",
    side_effects: "Nasopharyngitis, headache, joint pain.",
    precautions: "Monitor for hypersensitivity reactions like anaphylaxis or Stevens-Johnson syndrome.",
    producer_name: "Merck & Co. (MSD)",
    producer_country: "United States",
    producer_website: "https://www.merck.com"
  },
  {
    brand_name: "Linaglip",
    generic_name: "Linagliptin",
    dosage_form: "Tablet",
    strength: "5 mg",
    price: 18.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Dipeptidyl Peptidase-4 (DPP-4) Inhibitor",
    indications: "Type 2 diabetes mellitus. NO dose adjustment required in renal or hepatic impairment (bile excreted).",
    dosage_and_administration: "5 mg once daily anytime with or without food.",
    side_effects: "Nasopharyngitis, cough, mild pancreatitis risk.",
    precautions: "Ideal DPP-4 inhibitor for diabetic patients with chronic kidney disease (CKD).",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Trajenta",
    generic_name: "Linagliptin",
    dosage_form: "Tablet",
    strength: "5 mg",
    price: 38.00,
    currency: "EUR",
    package_info: "30 film-coated tablets",
    therapeutic_class: "Dipeptidyl Peptidase-4 (DPP-4) Inhibitor",
    indications: "Reference linagliptin for renal-safe glucose control.",
    dosage_and_administration: "5 mg once daily.",
    side_effects: "Hypoglycemia (only when combined with sulfonylurea or insulin), hyperlipidemia.",
    precautions: "Inform doctor if history of pancreatitis.",
    producer_name: "Boehringer Ingelheim",
    producer_country: "Germany",
    producer_website: "https://www.boehringer-ingelheim.com"
  },

  // Empagliflozin & Dapagliflozin (SGLT2 Inhibitors)
  {
    brand_name: "Emparol",
    generic_name: "Empagliflozin",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 25.00,
    currency: "BDT",
    package_info: "2 x 10 tablets",
    therapeutic_class: "Sodium-Glucose Co-Transporter 2 (SGLT2) Inhibitor",
    indications: "Type 2 diabetes, reduction of cardiovascular death, and treatment of heart failure with reduced or preserved ejection fraction.",
    dosage_and_administration: "10 mg once daily in morning. May be increased to 25 mg once daily.",
    side_effects: "Urinary tract infections (UTI), genital mycotic infections (thrush), polyuria, dehydration, rare euglycemic DKA.",
    precautions: "Maintain adequate hydration. Withhold before major surgery to prevent diabetic ketoacidosis.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Jardiance",
    generic_name: "Empagliflozin",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 48.00,
    currency: "USD",
    package_info: "30 tablets bottle",
    therapeutic_class: "Sodium-Glucose Co-Transporter 2 (SGLT2) Inhibitor",
    indications: "Landmark SGLT2 inhibitor proven to reduce cardiovascular mortality and heart failure hospitalization.",
    dosage_and_administration: "10 mg once daily in the morning.",
    side_effects: "Genitourinary infections, volume depletion.",
    precautions: "Monitor for signs of necrotizing fasciitis of the perineum (Fournier's gangrene).",
    producer_name: "Boehringer Ingelheim",
    producer_country: "Germany",
    producer_website: "https://www.boehringer-ingelheim.com"
  },
  {
    brand_name: "Dapacare",
    generic_name: "Dapagliflozin",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 24.00,
    currency: "BDT",
    package_info: "2 x 10 tablets",
    therapeutic_class: "Sodium-Glucose Co-Transporter 2 (SGLT2) Inhibitor",
    indications: "Glycemic control in type 2 diabetes, chronic kidney disease (CKD) progression reduction, and heart failure.",
    dosage_and_administration: "10 mg once daily in the morning with water.",
    side_effects: "Genital thrush, frequent urination, mild hypotension.",
    precautions: "Ensure fluid intake. Not recommended in type 1 diabetes.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Forxiga",
    generic_name: "Dapagliflozin",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 42.00,
    currency: "GBP",
    package_info: "28 film-coated tablets",
    therapeutic_class: "Sodium-Glucose Co-Transporter 2 (SGLT2) Inhibitor",
    indications: "Reference dapagliflozin for cardiorenal protection and glycemic control.",
    dosage_and_administration: "10 mg once daily.",
    side_effects: "Dysuria, fungal genital infection, thirst.",
    precautions: "Temporarily stop in acute severe illness with prolonged fasting.",
    producer_name: "AstraZeneca",
    producer_country: "United Kingdom",
    producer_website: "https://www.astrazeneca.com"
  },

  // ====================================================================
  // 5. ANTIBIOTICS & ANTIMICROBIALS
  // ====================================================================
  // Amoxicillin + Clavulanic Acid
  {
    brand_name: "Moxaclav",
    generic_name: "Amoxicillin + Clavulanic Acid",
    dosage_form: "Tablet",
    strength: "625 mg",
    price: 35.00,
    currency: "BDT",
    package_info: "2 x 8 film-coated tablets",
    therapeutic_class: "Broad-Spectrum Penicillin with Beta-Lactamase Inhibitor",
    indications: "Lower respiratory tract infections (pneumonia, bronchitis), otitis media, sinusitis, skin/soft tissue infections, and UTI.",
    dosage_and_administration: "Adults: 625 mg (500mg/125mg) every 8 hours or 1g every 12 hours at the START of a meal.",
    side_effects: "Diarrhea, nausea, vomiting, candidiasis, rare cholestatic jaundice/hepatitis.",
    precautions: "Contraindicated in history of penicillin allergy or penicillin-associated cholestatic jaundice. Take with food.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Tyclav",
    generic_name: "Amoxicillin + Clavulanic Acid",
    dosage_form: "Tablet",
    strength: "625 mg",
    price: 35.00,
    currency: "BDT",
    package_info: "2 x 8 film-coated tablets",
    therapeutic_class: "Broad-Spectrum Penicillin with Beta-Lactamase Inhibitor",
    indications: "Severe bacterial respiratory, dental, and urinary tract infections.",
    dosage_and_administration: "625 mg 3 times daily with meal.",
    side_effects: "Mild loose motions, oral thrush.",
    precautions: "Complete full prescribed course to prevent antibiotic resistance.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Augmentin",
    generic_name: "Amoxicillin + Clavulanic Acid",
    dosage_form: "Tablet",
    strength: "625 mg",
    price: 18.00,
    currency: "GBP",
    package_info: "14 film-coated tablets",
    therapeutic_class: "Broad-Spectrum Penicillin with Beta-Lactamase Inhibitor",
    indications: "World-renowned original co-amoxiclav for resistant beta-lactamase bacterial pathogens.",
    dosage_and_administration: "625 mg every 8 hours with meal.",
    side_effects: "Diarrhea, antibiotic-associated colitis, urticaria.",
    precautions: "Immediate emergency attention if wheezing or anaphylactic signs develop.",
    producer_name: "GlaxoSmithKline (GSK)",
    producer_country: "United Kingdom",
    producer_website: "https://www.gsk.com"
  },

  // Azithromycin
  {
    brand_name: "Zimax",
    generic_name: "Azithromycin",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 35.00,
    currency: "BDT",
    package_info: "3 x 4 tablets",
    therapeutic_class: "Macrolide Antibiotic",
    indications: "Community-acquired pneumonia, acute bacterial sinusitis, streptococcal pharyngitis/tonsillitis, skin infections, and urethritis/cervicitis.",
    dosage_and_administration: "Adults: 500 mg once daily for 3 consecutive days (or 500 mg on day 1, then 250 mg daily on days 2-5) 1 hr before or 2 hrs after meal.",
    side_effects: "Gastrointestinal cramping, diarrhea, nausea, temporary taste perversion, QT prolongation.",
    precautions: "Caution in patients with cardiac arrhythmias or baseline prolonged QT interval.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "A-One",
    generic_name: "Azithromycin",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 35.00,
    currency: "BDT",
    package_info: "3 x 4 tablets",
    therapeutic_class: "Macrolide Antibiotic",
    indications: "Respiratory infections, throat infections, and atypical pneumonia.",
    dosage_and_administration: "500 mg once daily 1 hour before meal for 3-5 days.",
    side_effects: "Abdominal discomfort, loose stools.",
    precautions: "Do not take antacids containing aluminum or magnesium simultaneously.",
    producer_name: "The Acme Laboratories Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.acmeglobal.com"
  },
  {
    brand_name: "Zithrox",
    generic_name: "Azithromycin",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 35.00,
    currency: "BDT",
    package_info: "3 x 4 tablets",
    therapeutic_class: "Macrolide Antibiotic",
    indications: "Bronchial infections, enteric fever, and chlamydial genital infections.",
    dosage_and_administration: "500 mg daily for 3-5 days.",
    side_effects: "Nausea, flatulence, headache.",
    precautions: "Avoid in patients with cholestatic jaundice history.",
    producer_name: "Incepta Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.inceptapharma.com"
  },
  {
    brand_name: "Zithromax",
    generic_name: "Azithromycin",
    dosage_form: "Tablet",
    strength: "250 mg",
    price: 25.00,
    currency: "USD",
    package_info: "6 tablets blister pack (Z-Pak)",
    therapeutic_class: "Macrolide Antibiotic",
    indications: "Iconic Z-Pak formulation for fast-resolving respiratory tract bacterial infections.",
    dosage_and_administration: "500 mg single dose Day 1, followed by 250 mg once daily Days 2 through 5.",
    side_effects: "Diarrhea, vomiting, headache.",
    precautions: "FDA alert on cardiovascular risks associated with prolonged QT interval.",
    producer_name: "Pfizer Inc.",
    producer_country: "United States",
    producer_website: "https://www.pfizer.com"
  },

  // Cefixime & Cefuroxime (Cephalosporins)
  {
    brand_name: "Cef-3",
    generic_name: "Cefixime Trihydrate",
    dosage_form: "Capsule",
    strength: "200 mg",
    price: 40.00,
    currency: "BDT",
    package_info: "2 x 7 capsules",
    therapeutic_class: "Third-Generation Cephalosporin Antibiotic",
    indications: "Enteric/Typhoid fever, acute exacerbation of chronic bronchitis, uncomplicated gonorrhea, and urinary tract infections.",
    dosage_and_administration: "Adults: 200-400 mg daily given either as a single dose or in two divided doses for 7-14 days.",
    side_effects: "Diarrhea, stool frequency changes, nausea, dyspepsia, pruritus.",
    precautions: "Cross-sensitivity in patients with severe IgE-mediated penicillin allergy.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Triocim",
    generic_name: "Cefixime Trihydrate",
    dosage_form: "Capsule",
    strength: "200 mg",
    price: 40.00,
    currency: "BDT",
    package_info: "2 x 7 capsules",
    therapeutic_class: "Third-Generation Cephalosporin Antibiotic",
    indications: "Salmonella typhi bacteremia, cystitis, and middle ear infections.",
    dosage_and_administration: "200 mg twice daily for 7-10 days.",
    side_effects: "Soft stools, dizziness.",
    precautions: "Dosage adjustment required in moderate to severe renal failure.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Kilbac",
    generic_name: "Cefuroxime Axetil",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 45.00,
    currency: "BDT",
    package_info: "2 x 7 tablets",
    therapeutic_class: "Second-Generation Cephalosporin Antibiotic",
    indications: "Acute bacterial maxillary sinusitis, Lyme disease, community-acquired pneumonia, skin/skin structure infections.",
    dosage_and_administration: "Adults: 250-500 mg twice daily with food for 7-10 days.",
    side_effects: "Gastrointestinal upset, Jarisch-Herxheimer reaction in Lyme disease, fungal overgrowth.",
    precautions: "MUST be taken with food to ensure maximal systemic bioavailability.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Ceftin",
    generic_name: "Cefuroxime Axetil",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 24.00,
    currency: "USD",
    package_info: "20 film-coated tablets",
    therapeutic_class: "Second-Generation Cephalosporin Antibiotic",
    indications: "Reference oral cephalosporin for beta-lactamase stable antibacterial therapy.",
    dosage_and_administration: "500 mg twice daily after meals.",
    side_effects: "Diarrhea, eosinophilia, transient AST/ALT elevations.",
    precautions: "Tablets should not be crushed due to strong bitter taste.",
    producer_name: "GlaxoSmithKline (GSK)",
    producer_country: "United Kingdom",
    producer_website: "https://www.gsk.com"
  },

  // Ciprofloxacin & Metronidazole
  {
    brand_name: "Neofloxin",
    generic_name: "Ciprofloxacin Hydrochloride",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 15.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Fluoroquinolone Antibacterial",
    indications: "Complicated urinary tract infections, infectious diarrhea (shigellosis, cholera), bone and joint infections, typhoid fever.",
    dosage_and_administration: "Adults: 500-750 mg twice daily with liberal fluid intake for 5-14 days.",
    side_effects: "Tendonitis and tendon rupture (Achilles), peripheral neuropathy, central nervous system stimulation, photosensitivity.",
    precautions: "FDA Boxed warning for tendon rupture. Avoid in children and adolescents during skeletal growth phase.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Cipro",
    generic_name: "Ciprofloxacin Hydrochloride",
    dosage_form: "Tablet",
    strength: "500 mg",
    price: 16.00,
    currency: "EUR",
    package_info: "20 film-coated tablets",
    therapeutic_class: "Fluoroquinolone Antibacterial",
    indications: "Original reference broad-spectrum quinolone for severe Gram-negative bacilli infections.",
    dosage_and_administration: "500 mg every 12 hours with copious water.",
    side_effects: "Nausea, phototoxicity, QT interval prolongation.",
    precautions: "Avoid dairy products and calcium-fortified juices within 2 hours of dosing.",
    producer_name: "Bayer AG",
    producer_country: "Germany",
    producer_website: "https://www.bayer.com"
  },
  {
    brand_name: "Filmet",
    generic_name: "Metronidazole",
    dosage_form: "Tablet",
    strength: "400 mg",
    price: 2.50,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Nitroimidazole Antiprotozoal & Antibacterial",
    indications: "Intestinal and hepatic amebiasis, giardiasis, trichomoniasis, anaerobic bacterial infections, and dental abscesses.",
    dosage_and_administration: "Adults: 400-800 mg 3 times daily with food for 5-10 days depending on indication.",
    side_effects: "Metallic taste, furred tongue, nausea, anorexia, dark reddish-brown urine.",
    precautions: "STRICTLY AVOID ALCOHOL during and for 48 hours after treatment (severe disulfiram-like flushing reaction).",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Flagyl",
    generic_name: "Metronidazole",
    dosage_form: "Tablet",
    strength: "400 mg",
    price: 9.00,
    currency: "EUR",
    package_info: "30 film-coated tablets",
    therapeutic_class: "Nitroimidazole Antiprotozoal & Antibacterial",
    indications: "Original reference anaerobic and antiprotozoal medication.",
    dosage_and_administration: "400 mg 3 times daily with food.",
    side_effects: "Severe disulfiram-like alcohol interaction, peripheral neuropathy with prolonged use.",
    precautions: "Do not consume any alcoholic beverages or medications containing alcohol.",
    producer_name: "Sanofi",
    producer_country: "France",
    producer_website: "https://www.sanofi.com"
  },

  // ====================================================================
  // 6. RESPIRATORY, ANTIHISTAMINES & ASTHMA
  // ====================================================================
  // Montelukast
  {
    brand_name: "Monas",
    generic_name: "Montelukast Sodium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 16.00,
    currency: "BDT",
    package_info: "3 x 10 film-coated tablets",
    therapeutic_class: "Leukotriene Receptor Antagonist (LTRA)",
    indications: "Prophylaxis and chronic treatment of asthma, prevention of exercise-induced bronchoconstriction, and allergic rhinitis.",
    dosage_and_administration: "Adults & adolescents (15+ yrs): 10 mg once daily taken in the evening with or without food.",
    side_effects: "Headache, abdominal pain, dream abnormalities, insomnia. Rare neuropsychiatric events.",
    precautions: "NOT indicated for relief of acute bronchospasm/asthma attacks. Monitor for mood changes.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Montene",
    generic_name: "Montelukast Sodium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 16.00,
    currency: "BDT",
    package_info: "3 x 10 film-coated tablets",
    therapeutic_class: "Leukotriene Receptor Antagonist (LTRA)",
    indications: "Year-round allergic rhinitis, perennial sneezing, and nocturnal asthma prevention.",
    dosage_and_administration: "10 mg once daily at bedtime.",
    side_effects: "Upper respiratory infection, drowsiness, pharyngitis.",
    precautions: "Keep short-acting rescue inhaler handy for sudden asthma flares.",
    producer_name: "Incepta Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.inceptapharma.com"
  },
  {
    brand_name: "Odmon",
    generic_name: "Montelukast Sodium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 16.00,
    currency: "BDT",
    package_info: "3 x 10 film-coated tablets",
    therapeutic_class: "Leukotriene Receptor Antagonist (LTRA)",
    indications: "Chronic bronchial asthma control and allergic nasal congestion.",
    dosage_and_administration: "10 mg once daily at evening.",
    side_effects: "Mild headache, fatigue.",
    precautions: "Report any behavioral changes or sleep disturbance to physician.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Singulair",
    generic_name: "Montelukast Sodium",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 32.00,
    currency: "USD",
    package_info: "30 film-coated tablets",
    therapeutic_class: "Leukotriene Receptor Antagonist (LTRA)",
    indications: "Original reference leukotriene inhibitor for asthma maintenance and seasonal allergies.",
    dosage_and_administration: "10 mg once daily in evening.",
    side_effects: "Headache, neuropsychiatric symptoms (agitation, depression).",
    precautions: "FDA Boxed Warning regarding neuropsychiatric events; discuss mental health history.",
    producer_name: "Merck & Co. (MSD)",
    producer_country: "United States",
    producer_website: "https://www.merck.com"
  },

  // Fexofenadine & Bilastine
  {
    brand_name: "Fexo",
    generic_name: "Fexofenadine Hydrochloride",
    dosage_form: "Tablet",
    strength: "120 mg",
    price: 8.00,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Second-Generation Non-Sedating Antihistamine",
    indications: "Seasonal allergic rhinitis (sneezing, runny nose, itchy throat) and chronic idiopathic urticaria (hives).",
    dosage_and_administration: "Adults: 120-180 mg once daily with water. Do not take with fruit juice.",
    side_effects: "Headache, dizziness, nausea. True non-sedating profile with minimal blood-brain barrier penetration.",
    precautions: "Do NOT take with grapefruit, apple, or orange juice (OATP1A2 inhibition reduces drug absorption by 50%).",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Fexodine",
    generic_name: "Fexofenadine Hydrochloride",
    dosage_form: "Tablet",
    strength: "120 mg",
    price: 8.00,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Second-Generation Non-Sedating Antihistamine",
    indications: "Allergy symptoms, dust allergy, and itchy skin dermatoses.",
    dosage_and_administration: "120 mg once daily with plain water.",
    side_effects: "Rare fatigue, dyspepsia.",
    precautions: "Avoid taking fruit juices within 2 hours of ingestion.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Allegra",
    generic_name: "Fexofenadine Hydrochloride",
    dosage_form: "Tablet",
    strength: "180 mg",
    price: 19.50,
    currency: "USD",
    package_info: "30 non-drowsy tablets",
    therapeutic_class: "Second-Generation Non-Sedating Antihistamine",
    indications: "Full 24-hour fast non-drowsy relief from outdoor and indoor environmental allergens.",
    dosage_and_administration: "180 mg once daily with water.",
    side_effects: "Mild dry mouth, headache.",
    precautions: "Space 2 hours away from aluminum or magnesium antacids.",
    producer_name: "Sanofi",
    producer_country: "France",
    producer_website: "https://www.sanofi.com"
  },
  {
    brand_name: "Bilaxten",
    generic_name: "Bilastine",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 16.00,
    currency: "EUR",
    package_info: "20 tablets",
    therapeutic_class: "Second-Generation Non-Sedating Antihistamine",
    indications: "Symptomatic treatment of allergic rhino-conjunctivitis and urticaria with zero sedative effect.",
    dosage_and_administration: "20 mg once daily taken 1 hour before or 2 hours after food or fruit juice.",
    side_effects: "Headache, somnolence (comparable to placebo).",
    precautions: "Must be taken on an empty stomach for maximum bioavailability.",
    producer_name: "Novartis",
    producer_country: "Switzerland",
    producer_website: "https://www.novartis.com"
  },
  {
    brand_name: "Bilast",
    generic_name: "Bilastine",
    dosage_form: "Tablet",
    strength: "20 mg",
    price: 15.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Second-Generation Non-Sedating Antihistamine",
    indications: "High affinity H1 receptor blockade for severe rhinitis and allergic eye symptoms.",
    dosage_and_administration: "20 mg once daily on empty stomach (1 hour before meals).",
    side_effects: "Extremely low incidence of drowsiness.",
    precautions: "Food decreases bilastine bioavailability by 30%. Take with pure water.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },

  // ====================================================================
  // 7. CNS, NEUROLOGY & PSYCHIATRIC
  // ====================================================================
  // Escitalopram (SSRI)
  {
    brand_name: "Esita",
    generic_name: "Escitalopram Oxalate",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 10.00,
    currency: "BDT",
    package_info: "3 x 10 tablets",
    therapeutic_class: "Selective Serotonin Reuptake Inhibitor (SSRI)",
    indications: "Major depressive disorder (MDD), generalized anxiety disorder (GAD), panic disorder with or without agoraphobia.",
    dosage_and_administration: "Initial: 10 mg once daily in morning or evening. May increase to maximum 20 mg daily after 2-4 weeks.",
    side_effects: "Nausea, insomnia, fatigue, sexual dysfunction (delayed ejaculation), dry mouth, serotonin syndrome (rare).",
    precautions: "Full therapeutic benefit takes 2-4 weeks. Do not discontinue abruptly (withdrawal syndrome). Black box warning for youth suicidal ideation.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Lexapro",
    generic_name: "Escitalopram Oxalate",
    dosage_form: "Tablet",
    strength: "10 mg",
    price: 28.00,
    currency: "USD",
    package_info: "30 film-coated tablets",
    therapeutic_class: "Selective Serotonin Reuptake Inhibitor (SSRI)",
    indications: "Original reference S-enantiomer SSRI for treatment of clinical depression and chronic anxiety.",
    dosage_and_administration: "10 mg once daily.",
    side_effects: "Nausea, changes in appetite, sexual dysfunction, hyponatremia.",
    precautions: "Contraindicated with MAO inhibitors or pimozide.",
    producer_name: "Pfizer Inc.",
    producer_country: "United States",
    producer_website: "https://www.pfizer.com"
  },

  // Clonazepam & Pregabalin
  {
    brand_name: "Disopan",
    generic_name: "Clonazepam",
    dosage_form: "Tablet",
    strength: "0.5 mg",
    price: 6.00,
    currency: "BDT",
    package_info: "5 x 10 tablets",
    therapeutic_class: "Benzodiazepine Anticonvulsant & Anxiolytic",
    indications: "Panic disorder, acute panic attacks, seizure disorders (myoclonic/absence seizures), and severe agoraphobia.",
    dosage_and_administration: "Panic disorder: 0.25-0.5 mg twice daily. Maximum 4 mg daily in divided doses. Use shortest possible duration.",
    side_effects: "Somnolence, ataxia, coordination impairment, behavioral changes, physical dependence and tolerance with prolonged use.",
    precautions: "CONTROLLED SUBSTANCE. Habit-forming. Gradual dose tapering required to prevent life-threatening rebound seizures.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Rivotril",
    generic_name: "Clonazepam",
    dosage_form: "Tablet",
    strength: "2 mg",
    price: 8.50,
    currency: "EUR",
    package_info: "30 scored tablets",
    therapeutic_class: "Benzodiazepine Anticonvulsant & Anxiolytic",
    indications: "Original reference clonazepam for refractory epileptic seizures and status epilepticus.",
    dosage_and_administration: "Individualized by neurologist.",
    side_effects: "Sedation, respiratory depression in high doses.",
    precautions: "Strict prescription only. Dangerous when co-administered with opioids or alcohol.",
    producer_name: "Roche",
    producer_country: "Switzerland",
    producer_website: "https://www.roche.com"
  },
  {
    brand_name: "Prelin",
    generic_name: "Pregabalin",
    dosage_form: "Capsule",
    strength: "50 mg",
    price: 12.00,
    currency: "BDT",
    package_info: "3 x 10 capsules",
    therapeutic_class: "GABA Analog (Neuropathic Pain Agent)",
    indications: "Neuropathic pain (diabetic peripheral neuropathy, post-herpetic neuralgia), fibromyalgia, spinal cord injury pain.",
    dosage_and_administration: "Initial: 50 mg 2-3 times daily (150 mg/day). May titrate up to 300-600 mg daily depending on clinical efficacy.",
    side_effects: "Dizziness, somnolence, peripheral edema, weight gain, blurred vision, dry mouth.",
    precautions: "Taper over at least 1 week when stopping. Dose adjustment required in renal insufficiency.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Lyrica",
    generic_name: "Pregabalin",
    dosage_form: "Capsule",
    strength: "75 mg",
    price: 36.00,
    currency: "USD",
    package_info: "30 capsules bottle",
    therapeutic_class: "GABA Analog (Neuropathic Pain Agent)",
    indications: "Original reference pregabalin for diabetic nerve pain and fibromyalgia relief.",
    dosage_and_administration: "75 mg twice daily or 50 mg 3 times daily.",
    side_effects: "Sedation, ataxia, euphoria, weight gain.",
    precautions: "Monitor for symptoms of drug misuse, mood changes, or suicidal thoughts.",
    producer_name: "Pfizer Inc.",
    producer_country: "United States",
    producer_website: "https://www.pfizer.com"
  },

  // ====================================================================
  // 8. VITAMINS, MINERALS & NUTRITIONAL SUPPLEMENTS
  // ====================================================================
  // Calcium + Vitamin D3
  {
    brand_name: "Coralcal-D",
    generic_name: "Coral Calcium + Vitamin D3",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    price: 12.00,
    currency: "BDT",
    package_info: "30 film-coated tablets container",
    therapeutic_class: "Mineral & Vitamin Supplement",
    indications: "Osteoporosis prevention, osteomalacia, rickets, pregnancy/lactation calcium support, and senior bone strength.",
    dosage_and_administration: "1 tablet once or twice daily with or immediately after meals.",
    side_effects: "Mild constipation, bloating, hypercalcemia with extreme overdose.",
    precautions: "Contraindicated in hypercalcemia, hypercalciuria, and kidney stones (nephrolithiasis).",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Calbo-D",
    generic_name: "Calcium Carbonate + Vitamin D3",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    price: 7.00,
    currency: "BDT",
    package_info: "30 film-coated tablets container",
    therapeutic_class: "Mineral & Vitamin Supplement",
    indications: "Dietary calcium supplementation and bone demineralization prophylaxis.",
    dosage_and_administration: "1 tablet once or twice daily with food.",
    side_effects: "Constipation, flatulence.",
    precautions: "Space 2 hours apart from iron supplements or fluoroquinolone antibiotics.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Ostocal-D",
    generic_name: "Calcium Carbonate + Vitamin D3",
    dosage_form: "Tablet",
    strength: "500 mg + 200 IU",
    price: 7.00,
    currency: "BDT",
    package_info: "30 film-coated tablets container",
    therapeutic_class: "Mineral & Vitamin Supplement",
    indications: "Bone health maintenance, postmenopausal osteoporosis, and fracture rehabilitation.",
    dosage_and_administration: "1 tablet twice daily with food.",
    side_effects: "Mild gastrointestinal fullness.",
    precautions: "Maintain adequate daily water hydration.",
    producer_name: "Beximco Pharmaceuticals Ltd.",
    producer_country: "Bangladesh",
    producer_website: "https://www.beximcopharma.com"
  },
  {
    brand_name: "Caltrate 600+D",
    generic_name: "Calcium Carbonate + Vitamin D3",
    dosage_form: "Tablet",
    strength: "600 mg + 800 IU",
    price: 14.50,
    currency: "USD",
    package_info: "60 tablets bottle",
    therapeutic_class: "Mineral & Vitamin Supplement",
    indications: "High-potency calcium plus maximum absorption vitamin D3 for bone density support.",
    dosage_and_administration: "1 tablet daily with food.",
    side_effects: "Constipation, nausea.",
    precautions: "Do not exceed recommended daily allowance.",
    producer_name: "GlaxoSmithKline (GSK)",
    producer_country: "United Kingdom",
    producer_website: "https://www.gsk.com"
  },

  // Vitamin B-Complex & Vitamin C
  {
    brand_name: "B-50 Forte",
    generic_name: "Vitamin B-Complex (Therapeutic)",
    dosage_form: "Tablet",
    strength: "High Potency B1, B2, B6, B12, Niacinamide",
    price: 2.50,
    currency: "BDT",
    package_info: "10 x 10 tablets",
    therapeutic_class: "Vitamin B-Complex Nutritional Supplement",
    indications: "Beriberi, peripheral neuritis, glossitis, stomatitis, chronic fatigue, alcohol-induced neuropathy, and convalescence.",
    dosage_and_administration: "Adults: 1-2 tablets daily or as prescribed by medical practitioner.",
    side_effects: "Bright yellow coloration of urine (harmless due to riboflavin excretion).",
    precautions: "Excessive doses of Vitamin B6 (pyridoxine) over extended months may cause sensory neuropathy.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Neurobion",
    generic_name: "Neurotropic Vitamin B (B1 + B6 + B12)",
    dosage_form: "Tablet",
    strength: "100 mg + 200 mg + 200 mcg",
    price: 8.50,
    currency: "EUR",
    package_info: "30 film-coated tablets",
    therapeutic_class: "Neurotropic Vitamin Complex",
    indications: "Neuropathy, numbness, tingling in hands and feet, neuralgias, and nerve regeneration.",
    dosage_and_administration: "1 tablet 1-3 times daily with water.",
    side_effects: "Chromaturia (yellow urine), mild sweating.",
    precautions: "Do not exceed 6 months continuous therapy without doctor review.",
    producer_name: "Merck & Co. (MSD)",
    producer_country: "United States",
    producer_website: "https://www.merck.com"
  },
  {
    brand_name: "Ceevit",
    generic_name: "Ascorbic Acid (Vitamin C)",
    dosage_form: "Chewable Tablet",
    strength: "250 mg",
    price: 2.00,
    currency: "BDT",
    package_info: "10 x 10 chewable tablets",
    therapeutic_class: "Water-Soluble Vitamin & Antioxidant",
    indications: "Scurvy, wound healing, collagen synthesis, immune defense enhancement against seasonal viral infections.",
    dosage_and_administration: "Adults: 1-2 chewable tablets daily dissolved in mouth.",
    side_effects: "Safe water-soluble vitamin. Massive doses (>2g/day) may cause diarrhea and oxalate kidney stones.",
    precautions: "Caution in recurrent renal calcium oxalate stone formers.",
    producer_name: "Square Pharmaceuticals PLC",
    producer_country: "Bangladesh",
    producer_website: "https://www.squarepharma.com.bd"
  },
  {
    brand_name: "Redoxon",
    generic_name: "Ascorbic Acid (Vitamin C) + Zinc",
    dosage_form: "Effervescent Tablet",
    strength: "1000 mg + 10 mg",
    price: 9.00,
    currency: "EUR",
    package_info: "15 effervescent tablets tube",
    therapeutic_class: "Immune Support & Antioxidant",
    indications: "Immune defense booster and antioxidant cell protection.",
    dosage_and_administration: "1 tablet fully dissolved in a glass of water daily.",
    side_effects: "Mild stomach acidity, osmotic diarrhea at excess doses.",
    precautions: "Contains sodium; monitor in strict low-sodium diets.",
    producer_name: "Bayer AG",
    producer_country: "Germany",
    producer_website: "https://www.bayer.com"
  }
];

// ----------------------------------------------------------------------
// Database Ingestion Engine
// ----------------------------------------------------------------------
async function importAllMedicines() {
  console.log('================================================================');
  console.log('  Permanent Bulk Importer: Supabase Medicine Database');
  console.log(`  Total Curated Medicines to Process: ${MEDICINES_DATASET.length}`);
  console.log('================================================================\n');

  const connectionString = process.env.DATABASE_URL ||
    'postgresql://postgres:3-Xjs*a*KsXb6H5@db.nxwjkawsnjrebxzdkedl.supabase.co:5432/postgres';

  const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false }
  });

  try {
    console.log('🔌 Connecting to PostgreSQL at db.nxwjkawsnjrebxzdkedl.supabase.co...');
    await client.connect();
    console.log('✅ Connected successfully!\n');

    let insertedCount = 0;
    let bangladeshCount = 0;
    let globalCount = 0;

    for (let i = 0; i < MEDICINES_DATASET.length; i++) {
      const item = MEDICINES_DATASET[i];
      const isBd = item.producer_country.toLowerCase() === 'bangladesh';

      if (isBd) bangladeshCount++;
      else globalCount++;

      const query = `
        SELECT upsert_medicine_record(
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
        );
      `;

      const values = [
        item.brand_name,
        item.generic_name,
        item.producer_name,
        item.producer_country,
        item.dosage_form,
        item.strength,
        item.price,
        item.currency,
        item.package_info,
        item.therapeutic_class,
        item.indications,
        item.dosage_and_administration,
        item.side_effects,
        item.precautions,
        item.producer_website || null
      ];

      await client.query(query, values);
      insertedCount++;

      if (insertedCount % 10 === 0 || insertedCount === MEDICINES_DATASET.length) {
        process.stdout.write(`  ⏳ Processed ${insertedCount}/${MEDICINES_DATASET.length} medicines...\r`);
      }
    }

    console.log(`\n\n🎉 Successfully processed and upserted ${insertedCount} medicines permanently!`);

    // Verify final counts in database
    const resMeds = await client.query('SELECT count(*) FROM medicines;');
    const resGen = await client.query('SELECT count(*) FROM generics;');
    const resProd = await client.query('SELECT count(*) FROM producers;');
    const resBdMeds = await client.query("SELECT count(*) FROM view_medicines_directory WHERE LOWER(producer_country) = 'bangladesh';");

    console.log('\n================================================================');
    console.log('             FINAL DATABASE VERIFICATION AUDIT                 ');
    console.log('================================================================');
    console.log(`  📦 Total Medicines in DB:     ${resMeds.rows[0].count}`);
    console.log(`  🇧🇩 Bangladesh Priority Meds: ${resBdMeds.rows[0].count}`);
    console.log(`  🌐 Global Medicines in DB:    ${Number(resMeds.rows[0].count) - Number(resBdMeds.rows[0].count)}`);
    console.log(`  💊 Total Generics in DB:      ${resGen.rows[0].count}`);
    console.log(`  🏢 Total Producers in DB:     ${resProd.rows[0].count}`);
    console.log('================================================================\n');

  } catch (err) {
    console.error('❌ Ingestion Error:', err);
    process.exit(1);
  } finally {
    await client.end();
  }
}

importAllMedicines();
